---
- name: Setup NFS Server
  hosts: nfs_servers # On utilise un groupe clair
  become: true
  tasks:
    - name: Installer le serveur NFS et activer ufw
      apt:
        name: [nfs-kernel-server, ufw]
        state: present
        update_cache: true

    - name: Autoriser les ports nécessaires (NFS et SSH)
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
       - { port: '2049', proto: 'tcp' }
       - { port: '22', proto: 'tcp' }

    - name: Activer le pare-feu
      ufw:
        state: enabled

    - name: Créer le dossier à partager
      file:
        path: /srv/nfs/home
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configurer l’export NFS
      copy:
        dest: /etc/exports
        content: |
          /srv/nfs/home 192.168.2.0/24(rw,sync,no_subtree_check,no_root_squash)
          # no_root_squash est pratique pour les labs mais peut être un risque de sécurité en production.

    - name: Redémarrer et activer le service NFS
      systemd:
        name: nfs-server
        enabled: true
        state: restarted
