---
- name: Setup NFS Server
  hosts: nfs
  become: true
  tasks:
    - name: ouvrir le port 2049
      ufw:
        rule: allow
        port: "2049"
        proto: tcp

    - name: Installer le serveur NFS
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Créer le dossier à partager
      file:
        path: /srv/nfs/home
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configurer l’export NFS
      copy:
        dest: /etc/exports
        content: |
          /srv/nfs/home 192.168.2.0/16(rw,sync,no_subtree_check,no_root_squash)

    - name: Redémarrer le service NFS
      systemd:
        name: nfs-server
        enabled: true
        state: restarted

